# Generated by Django 6.0.4 on 2026-05-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название страницы')),
                ('image', models.ImageField(upload_to='paper_menu/', verbose_name='Изображение страницы меню')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Страница бумажного меню',
                'verbose_name_plural': 'Страницы бумажного меню',
                'ordering': ['order'],
            },
        ),
    ]
