# Generated by Django 6.0.7 on 2026-07-09 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations_count', models.IntegerField(default=5, help_text='Сколько блюд показывать в блоке рекомендаций (3-12)', validators=[django.core.validators.MinValueValidator(3)], verbose_name='Количество рекомендаций')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
